### ISSUE TITLE
Support having unlisted pages

### ISSUE THREAD

**Issue by mthaddon** [canonical/discourse-gatekeeper#25]
After some recent discussions with the Documentation team I was asked to remove the link to the "Roadmap" page (https://charmhub.io/nginx-ingress-integrator/docs/roadmap) from the navigation. It's linked in the README directly, and was felt to be unnecessary to list separately in the navigation.

To do so I had to add the following the *end* of the discourse navigation table in the /docs/ index:
```
|  | roadmap | [Roadmap](/t/nginx-ingress-integrator-docs-roadmap/7432) |
```
Apparently it breaks if it's not the last element (hopefully if you need multiple hidden elements that possible too...

Is it possible for this project to support that somehow?

**Comment by jdkandersson** [comment]
Yes it should be possible, I can see how this works. I assume that if the `level` field is not filled in, it doesn't show up but can be linked to.

We should combine this with #12 and essentially add a configuration file potentially something like:

```yaml
files:
  <relative path in docs folder>:
    rank: <number indicating the rank, the lower the higher it is listed in its directory, defaults to ranked alphabetically for those items without a rank>
    listed: <boolean for whether to list it in the navigation, defaults to true>
```

@gregory-schiano any comment?
