### ISSUE TITLE
Custom metadata.yaml location

### ISSUE THREAD

**Issue by barrettj12** [canonical/discourse-gatekeeper#39]
We are interested in using this action to publish Juju docs (which use a similar structure to charm docs).

As it stands, the `metadata.yaml` file has to be in the root directory of the repository. For Juju, we don't want to have to add a `metadata.yaml` in the root directory just for this action to work. We'd be happy to place the `metadata.yaml` in e.g. the `docs` or `.github` directories.

I see two solutions:
1. Add an action input to allow a custom `metadata.yaml` location.
   ```yaml
   uses: canonical/upload-charm-docs
   with:
     metadata-location: '.github/docs-config.yaml'
   ```
2. Add action inputs to allow specifying the required metadata directly.
   ```yaml
   uses: canonical/upload-charm-docs
   with:
     charm-name: 'juju'
     index-page-url: 'https://discourse.charmhub.io/t/juju-olm-documentation/1087'
   ```
